#Login Page Elements
txt_loginUserName="name:userName"
txt_loginPassword="name:password"
btn_signIn="name:login"

#Registration Page Elements
link_Reg="link:REGISTER"
txt_firstName="name:firstName"
txt_lastName="name:lastName"
txt_phone="name:phone"
txt_email="name:userName"
txt_add1="name:address1"
txt_add2="name:address2"
txt_city="name:city"
txt_state="name:state"
txt_postCode="name:postalCode"
drp_country="name:country"
txt_userName="name:email"
txt_Password="name:password"
txt_confirmPassword="name:confirmPassword"
btn_submit="name:register"
